////////////////////////////////////////////////////////////////////////////////////////////////////
// Lukoi NPC Templates
////////////////////////////////////////////////////////////////////////////////////////////////////

// Lukoi Brute, Basic ------------------------------------------------------------------------------
kantia.template.npcs["Lukoi Brute, Basic"] = new kantia.template.npc(
	"Lukoi Brute, Basic",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",14,18,16),
		"size": new kantia.template.npcAttribute("Size",14,17,16),
		"agility": new kantia.template.npcAttribute("Agility",8,12,10),
		"reflexes": new kantia.template.npcAttribute("Reflexes",8,10,10),
		"constitution": new kantia.template.npcAttribute("Constitution",13,15,14),
		"fortitude": new kantia.template.npcAttribute("Fortitude",14,18,16),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,7),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,8),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,8),
		"perception": new kantia.template.npcAttribute("Perception",8,14,12)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",8),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",5),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",4),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",5),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",3),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],4),
		"Intimidation": new kantia.template.npcSkill("Intimidation","strength",8),
		"Knowledge Skill": new kantia.template.npcSkill("Knowledge Skill","reasoning",6),
		"Listen": new kantia.template.npcSkill("Listen","perception",4),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],4),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",4),
		"Professional Skill": new kantia.template.npcSkill("Professional Skill","reasoning",4),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",8),
		"Smell": new kantia.template.npcSkill("Smell","perception",4),
		"Spot": new kantia.template.npcSkill("Spot","perception",6),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",4),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",8),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",8)
	},
	{
		"Adrenaline": new kantia.template.npcTrait("Adrenaline",1),
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Fast Healing": new kantia.template.npcTrait("Fast Healing",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Missing Eye": new kantia.template.npcTrait("Missing Eye",1),
		"Missing Finger": new kantia.template.npcTrait("Missing Finger",1),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",4),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",4),
		"Leathal Strike Mastery": new kantia.template.npcMastery("Leathal Strike Mastery",4)
	},
	[
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Berserker",2),
		new kantia.template.npcHC("Combat Intuition",2),
		new kantia.template.npcHC("Combat Reflexes",4),
		new kantia.template.npcHC("Deep Roots",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Hermit's Stride",1),
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Robust Health",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Take'em ALl",1),
		new kantia.template.npcHC("Thick Skinned",1),
		new kantia.template.npcHC("Tough as Nails",1)
	],
	["Leather Jerkin","Leather Vambrace","Leather Greaves"],
	{
		"melee": ["Light Club","Medium Club, 1H","Medium Club, 2H","Heavy Club","Battle Axe, 1H","Battle Axe, 2H","Great Axe","Footman's Pick, 1H","Footman's Pick, 2H","Greatsword","Wood Axe","Pick-Axe","Dagger"],
		"ranged": []
	},
	"",
	"These NPCs often have few possessions, although what they do own is often very durable and sturdy. Wilderness types will often carry any survival equipment they need with them at all times, while urban types often only carry what they will need in the immediate future. The average brute has 1d3-1 crowns, 2d6-2 silver, and 2d10 copper.",
	"A basic template for a large, combat oriented brute characters, barbarians, enforcers, bouncers and similar characters.  These characters are typically melee oriented, although some wilderness types use ranged weapons.",
	[]
);

// Lukoi Brute, Expert -----------------------------------------------------------------------------
kantia.template.npcs["Lukoi Brute, Expert"] = new kantia.template.npc(
	"Lukoi Brute, Expert",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",13,15,15),
		"size": new kantia.template.npcAttribute("Size",13,15,15),
		"agility": new kantia.template.npcAttribute("Agility",8,12,10),
		"reflexes": new kantia.template.npcAttribute("Reflexes",8,12,10),
		"constitution": new kantia.template.npcAttribute("Constitution",13,15,15),
		"fortitude": new kantia.template.npcAttribute("Fortitude",13,15,15),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,8),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,8),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,8),
		"perception": new kantia.template.npcAttribute("Perception",6,12,10)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",12),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",6),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",6),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",8),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",5),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],6),
		"Intimidation": new kantia.template.npcSkill("Intimidation","strength",14),
		"Knowledge Skill": new kantia.template.npcSkill("Knowledge Skill","reasoning",8),
		"Listen": new kantia.template.npcSkill("Listen","perception",6),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],6),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",6),
		"Professional Skill": new kantia.template.npcSkill("Professional Skill","reasoning",6),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",12),
		"Smell": new kantia.template.npcSkill("Smell","perception",6),
		"Spot": new kantia.template.npcSkill("Spot","perception",8),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",6),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",12),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",12)
	},
	{
		"Adrenaline": new kantia.template.npcTrait("Adrenaline",1),
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Fast Healing": new kantia.template.npcTrait("Fast Healing",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Missing Eye": new kantia.template.npcTrait("Missing Eye",1),
		"Missing Finger": new kantia.template.npcTrait("Missing Finger",1),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",6),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",8),
		"Multiple Attack - 3rd Attack": new kantia.template.npcMastery("Multiple Attack - 3rd Attack",4),
		"Leathal Strike Mastery": new kantia.template.npcMastery("Leathal Strike Mastery",8)
	},
	[
		new kantia.template.npcHC("Alertness",2),
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Berserker",4),
		new kantia.template.npcHC("Combat Intuition",3),
		new kantia.template.npcHC("Combat Reflexes",4),
		new kantia.template.npcHC("Danger Sense",1),
		new kantia.template.npcHC("Deep Roots",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Flashy Warrior",1),
		new kantia.template.npcHC("Hermit's Stride",1),
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Robust Health",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Take'em ALl",2),
		new kantia.template.npcHC("The Stare",1),
		new kantia.template.npcHC("Thick Skinned",1),
		new kantia.template.npcHC("Tough as Nails",2)
	],
	["Leather Jerkin","Leather Vambrace","Leather Greaves"],
	{
		"melee": ["Light Club","Medium Club, 1H","Medium Club, 2H","Heavy Club","Battle Axe, 1H","Battle Axe, 2H","Great Axe","Footman's Pick, 1H","Footman's Pick, 2H","Greatsword","Wood Axe","Pick-Axe","Dagger"],
		"ranged": []
	},
	"",
	"These NPCs often have few possessions, although what they do own is often very durable and sturdy. Wilderness types will often carry any survival equipment they need with them at all times, while urban types often only carry what they will need in the immediate future. The average brute has 1d3 crowns, 2d6 silver, and 2d10 copper.",
	"A basic template for a large, combat oriented brute characters, barbarians, enforcers, bouncers and similar characters.  These characters are typically melee oriented, although some wilderness types use ranged weapons.",
	[]
);

// Lukoi Brute, Master -----------------------------------------------------------------------------
kantia.template.npcs["Lukoi Brute, Master"] = new kantia.template.npc(
	"Lukoi Brute, Master",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",13,15,16),
		"size": new kantia.template.npcAttribute("Size",13,15,15),
		"agility": new kantia.template.npcAttribute("Agility",8,12,10),
		"reflexes": new kantia.template.npcAttribute("Reflexes",8,12,10),
		"constitution": new kantia.template.npcAttribute("Constitution",13,15,15),
		"fortitude": new kantia.template.npcAttribute("Fortitude",13,15,16),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,9),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,8),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,8),
		"perception": new kantia.template.npcAttribute("Perception",6,12,10)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",12),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",6),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",6),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",8),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",7),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],6),
		"Intimidation": new kantia.template.npcSkill("Intimidation","strength",14),
		"Knowledge Skill": new kantia.template.npcSkill("Knowledge Skill","reasoning",8),
		"Listen": new kantia.template.npcSkill("Listen","perception",6),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],6),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",6),
		"Professional Skill": new kantia.template.npcSkill("Professional Skill","reasoning",6),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",12),
		"Smell": new kantia.template.npcSkill("Smell","perception",6),
		"Spot": new kantia.template.npcSkill("Spot","perception",8),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",6),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",12),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",12)
	},
	{
		"Adrenaline": new kantia.template.npcTrait("Adrenaline",1),
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Fast Healing": new kantia.template.npcTrait("Fast Healing",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Missing Eye": new kantia.template.npcTrait("Missing Eye",1),
		"Missing Finger": new kantia.template.npcTrait("Missing Finger",1),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",8),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",12),
		"Multiple Attack - 3rd Attack": new kantia.template.npcMastery("Multiple Attack - 3rd Attack",8),
		"Multiple Attack - 4th Attack": new kantia.template.npcMastery("Multiple Attack - 4th Attack",4),
		"Leathal Strike Mastery": new kantia.template.npcMastery("Leathal Strike Mastery",12)
	},
	[
		new kantia.template.npcHC("Alertness",4),
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Berserker",6),
		new kantia.template.npcHC("Combat Intuition",4),
		new kantia.template.npcHC("Combat Reflexes",6),
		new kantia.template.npcHC("Danger Sense",1),
		new kantia.template.npcHC("Deep Roots",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Flashy Warrior",1),
		new kantia.template.npcHC("Hermit's Stride",1),
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Robust Health",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Take'em ALl",2),
		new kantia.template.npcHC("The Stare",1),
		new kantia.template.npcHC("Thick Skinned",3),
		new kantia.template.npcHC("Tough as Nails",2)
	],
	["Leather Jerkin","Leather Vambrace","Leather Greaves"],
	{
		"melee": ["Light Club","Medium Club, 1H","Medium Club, 2H","Heavy Club","Battle Axe, 1H","Battle Axe, 2H","Great Axe","Footman's Pick, 1H","Footman's Pick, 2H","Greatsword","Wood Axe","Pick-Axe","Dagger"],
		"ranged": []
	},
	"",
	"These NPCs often have few possessions, although what they do own is often very durable and sturdy, although brutes of this skill and power may possess luxuries and some premium equipment. Wilderness types will often carry any survival equipment they need with them at all times, while urban types often only carry what they will need in the immediate future. The average brute has 1d6 crowns, 2d8 silver, and 2d10 copper.",
	"A basic template for a large, combat oriented brute characters, barbarians, enforcers, bouncers and similar characters.  These characters are typically melee oriented, although some wilderness types use ranged weapons.",
	[]
);

// Lukoi Fighter, Basic ----------------------------------------------------------------------------
kantia.template.npcs["Lukoi Fighter, Basic"] = new kantia.template.npc(
	"Lukoi Fighter, Basic",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",12,17,15),
		"size": new kantia.template.npcAttribute("Size",12,17,14),
		"agility": new kantia.template.npcAttribute("Agility",9,14,12),
		"reflexes": new kantia.template.npcAttribute("Reflexes",9,14,12),
		"constitution": new kantia.template.npcAttribute("Constitution",6,12,10),
		"fortitude": new kantia.template.npcAttribute("Fortitude",10,16,14),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,9),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,9),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,9),
		"perception": new kantia.template.npcAttribute("Perception",9,14,12)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",6),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",4),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",4),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",6),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",4),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],4),
		"Knowledge Skills": new kantia.template.npcSkill("Knowledge Skills","reasoning",6),
		"Listen": new kantia.template.npcSkill("Listen","perception",4),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],4),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",4),
		"Professional Skills": new kantia.template.npcSkill("Professional Skills","reasoning",6),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",6),
		"Smell": new kantia.template.npcSkill("Smell","perception",6),
		"Spot": new kantia.template.npcSkill("Spot","perception",6),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",4),
		"Tracking": new kantia.template.npcSkill("Tracking","perception",4),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",8),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",8)
	},
	{
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Animal Empathy": new kantia.template.npcTrait("Animal Empathy",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Code of Honor": new kantia.template.npcTrait("Code of Honor",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Light Footed": new kantia.template.npcTrait("Light Footed",1),
		"Light Sleeper": new kantia.template.npcTrait("Light Sleeper",1),
		"Lone Wolf": new kantia.template.npcTrait("Lone Wolf",1),
		"Lucky": new kantia.template.npcTrait("Lucky",6),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Suave": new kantia.template.npcTrait("Suave",1),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",4),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",4),
		"Lethal Strike Mastery": new kantia.template.npcMastery("Lethal Strike Mastery",4)
	},
	[
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Thich Skinned",1),
		new kantia.template.npcHC("Tough as Nails",1),
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Alert Sleeper",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Combat Reflexes",4),
		new kantia.template.npcHC("Combat Intuition",4),
		new kantia.template.npcHC("Cool Headed",1),
		new kantia.template.npcHC("Steadfast",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Tactician",1)
	],
	["Chain Shirt","Reinforced Bracers"],
	{
		"melee": kantia.lists.weapons.melee.all.slice(),
		"ranged": kantia.lists.weapons.ranged.all.slice()
	},
	"",
	"These NPCs do not have a preferred set of weapons and most listed weapons in the player's guide are acceptable. Equipment is typically of average quality, sometimes being well worn but usually well kept. Depending upon whether or not the NPC is near his home, he may or may not have more personal posessions besides standard equipment. While not rich, these NPCs tend to carry more money than simple commoners, though they sometimes spend their money un-wisely. Assume these NPCs carry 1d4 gold crowns, 1d8 silver shillings, and 2d10 copper if they would have any reason for carrying their money on their person (or adjust for the campaign).",
	"The fighter template focuses on NPCs that have a talent for traditional melee combat. Many are soldiers, mercenaries, town watch, bandits, and bounty hunters. They are well-skilled and capable individuals that are equally efficient if working alone or with others. They lead rough and often very dangerous lives and their personalities and attitudes will reflect that. NPC Fighters are vaguely classified into three types: basic, expert, and master.",
	[]
);

// Lukoi Fighter, Expert ------------------------------------------------------------------------------
kantia.template.npcs["Lukoi Fighter, Expert"] = new kantia.template.npc(
	"Lukoi Fighter, Expert",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",12,17,16),
		"size": new kantia.template.npcAttribute("Size",12,17,14),
		"agility": new kantia.template.npcAttribute("Agility",9,14,12),
		"reflexes": new kantia.template.npcAttribute("Reflexes",9,14,12),
		"constitution": new kantia.template.npcAttribute("Constitution",6,12,11),
		"fortitude": new kantia.template.npcAttribute("Fortitude",10,16,15),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,10),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,10),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,9),
		"perception": new kantia.template.npcAttribute("Perception",9,14,12)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",8),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",6),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",6),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",10),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",6),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],6),
		"Knowledge Skills": new kantia.template.npcSkill("Knowledge Skills","reasoning",8),
		"Listen": new kantia.template.npcSkill("Listen","perception",6),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],6),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",6),
		"Professional Skills": new kantia.template.npcSkill("Professional Skills","reasoning",8),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",8),
		"Smell": new kantia.template.npcSkill("Smell","perception",8),
		"Spot": new kantia.template.npcSkill("Spot","perception",8),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",4),
		"Tracking": new kantia.template.npcSkill("Tracking","perception",4),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",12),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",12)
	},
	{
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Animal Empathy": new kantia.template.npcTrait("Animal Empathy",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Code of Honor": new kantia.template.npcTrait("Code of Honor",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Light Footed": new kantia.template.npcTrait("Light Footed",1),
		"Light Sleeper": new kantia.template.npcTrait("Light Sleeper",1),
		"Lone Wolf": new kantia.template.npcTrait("Lone Wolf",1),
		"Lucky": new kantia.template.npcTrait("Lucky",6),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Suave": new kantia.template.npcTrait("Suave",1),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",6),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",8),
		"Multiple Attack - 3rd Attack": new kantia.template.npcMastery("Multiple Attack - 3rd Attack",4),
		"Lethal Strike Mastery": new kantia.template.npcMastery("Lethal Strike Mastery",6),
		"Weapon Defense": new kantia.template.npcMastery("Weapon Defense",5)
	},
	[
		new kantia.template.npcHC("Alert Sleeper",1),
		new kantia.template.npcHC("Alertness",1),
		new kantia.template.npcHC("Attack Precision",1),
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Blind Fighting",1),
		new kantia.template.npcHC("Combat Intuition",4),
		new kantia.template.npcHC("Combat Reflexes",8),
		new kantia.template.npcHC("Commanding Presence",1),
		new kantia.template.npcHC("Cool Headed",1),
		new kantia.template.npcHC("Crippling Strike",1),
		new kantia.template.npcHC("Danger Sense",1),
		new kantia.template.npcHC("Dead Eye Aim",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Flashy Warrior",1),
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Killing Blow",1),
		new kantia.template.npcHC("Leadership",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Shoot 'em All",1),
		new kantia.template.npcHC("Steadfast",1),
		new kantia.template.npcHC("Tactician",1),
		new kantia.template.npcHC("Take 'em All",1),
		new kantia.template.npcHC("The Stare",1),
		new kantia.template.npcHC("Thich Skinned",2),
		new kantia.template.npcHC("Tough as Nails",2),
		new kantia.template.npcHC("Weapon Shield",1),
		new kantia.template.npcHC("Weapon Technique",1)
	],
	["Chain Shirt","Reinforced Bracers"],
	{
		"melee": kantia.lists.weapons.melee.all.slice(),
		"ranged": kantia.lists.weapons.ranged.all.slice()
	},
	"",
	"Experienced military NPCs like this tend to carry good to high quality equipment. Some of it may actually be much better than standard issue. While they may not always carry money on themselves, it wouldn't be uncommon to find. High-Level fighting types usually carry about 2d6 crowns, 2d12 silver, and 2d10 copper.",
	"The fighter template focuses on NPCs that have a talent for traditional melee combat. Many are soldiers, mercenaries, town watch, bandits, and bounty hunters. They are well-skilled and capable individuals that are equally efficient if working alone or with others. They lead rough and often very dangerous lives and their personalities and attitudes will reflect that. NPC Fighters are vaguely classified into three types: basic, expert, and master.",
	[]
);

// Lukoi Fighter, Master ------------------------------------------------------------------------------
kantia.template.npcs["Lukoi Fighter, Master"] = new kantia.template.npc(
	"Lukoi Fighter, Master",
	"Lukoi",
	{
		"strength": new kantia.template.npcAttribute("Strength",12,17,16),
		"size": new kantia.template.npcAttribute("Size",12,17,14),
		"agility": new kantia.template.npcAttribute("Agility",9,14,13),
		"reflexes": new kantia.template.npcAttribute("Reflexes",9,14,12),
		"constitution": new kantia.template.npcAttribute("Constitution",6,12,12),
		"fortitude": new kantia.template.npcAttribute("Fortitude",10,16,16),
		"reasoning": new kantia.template.npcAttribute("Reasoning",6,12,11),
		"willpower": new kantia.template.npcAttribute("Willpower",6,12,10),
		"spirit": new kantia.template.npcAttribute("Spirit",6,12,9),
		"perception": new kantia.template.npcAttribute("Perception",9,14,12)
	},
	{
		"Brawling": new kantia.template.npcSkill("Brawling","agility",10),
		"Climbing": new kantia.template.npcSkill("Climbing","strength",8),
		"Determine Motivation": new kantia.template.npcSkill("Determine Motivation","reasoning",6),
		"Dodge": new kantia.template.npcSkill("Dodge","reflexes",12),
		"Feint": new kantia.template.npcSkill("Feint","reasoning",8),
		"Hide": new kantia.template.npcSkill("Hide",["agility","size"],8),
		"Knowledge Skills": new kantia.template.npcSkill("Knowledge Skills","reasoning",8),
		"Listen": new kantia.template.npcSkill("Listen","perception",6),
		"Move Silently": new kantia.template.npcSkill("Move Silently",["agility","size"],8),
		"Persuasion": new kantia.template.npcSkill("Persuasion","reasoning",6),
		"Professional Skills": new kantia.template.npcSkill("Professional Skills","reasoning",8),
		"Simple Weapons": new kantia.template.npcSkill("Simple Weapons","agility",8),
		"Smell": new kantia.template.npcSkill("Smell","perception",8),
		"Spot": new kantia.template.npcSkill("Spot","perception",8),
		"Street Saavy": new kantia.template.npcSkill("Street Saavy","reasoning",4),
		"Tracking": new kantia.template.npcSkill("Tracking","perception",6),
		"Weapon of Choice (Agility)": new kantia.template.npcSkill("Weapon of Choice (Agility)","agility",16),
		"Weapon of Choice (Perception)": new kantia.template.npcSkill("Weapon of Choice (Perception)","perception",16)
	},
	{
		"Ambidextrious": new kantia.template.npcTrait("Ambidextrious",1),
		"Animal Empathy": new kantia.template.npcTrait("Animal Empathy",1),
		"Branded": new kantia.template.npcTrait("Branded",1),
		"Code of Honor": new kantia.template.npcTrait("Code of Honor",1),
		"Combat Experience": new kantia.template.npcTrait("Combat Experience",1),
		"Habit": new kantia.template.npcTrait("Habit",1),
		"Half-Breed": new kantia.template.npcTrait("Half-Breed",1),
		"Impulsive": new kantia.template.npcTrait("Impulsive",1),
		"Light Footed": new kantia.template.npcTrait("Light Footed",1),
		"Light Sleeper": new kantia.template.npcTrait("Light Sleeper",1),
		"Lone Wolf": new kantia.template.npcTrait("Lone Wolf",1),
		"Lucky": new kantia.template.npcTrait("Lucky",6),
		"Ruthless": new kantia.template.npcTrait("Ruthless",1),
		"Skeptical": new kantia.template.npcTrait("Skeptical",1),
		"Spirit Sink": new kantia.template.npcTrait("Spirit Sink",4),
		"Suave": new kantia.template.npcTrait("Suave",1),
		"Uneducated": new kantia.template.npcTrait("Uneducated",1),
		"Void": new kantia.template.npcTrait("Void",1)
	},
	{
		"Two Weapon Mastery": new kantia.template.npcMastery("Two Weapon Mastery",8),
		"Multiple Attack - 2nd Attack": new kantia.template.npcMastery("Multiple Attack - 2nd Attack",12),
		"Multiple Attack - 3rd Attack": new kantia.template.npcMastery("Multiple Attack - 3rd Attack",8),
		"Multiple Attack - 4th Attack": new kantia.template.npcMastery("Multiple Attack - 4th Attack",4),
		"Lethal Strike Mastery": new kantia.template.npcMastery("Lethal Strike Mastery",8),
		"Weapon Defense": new kantia.template.npcMastery("Weapon Defense",10)
	},
	[
		new kantia.template.npcHC("Alert Sleeper",1),
		new kantia.template.npcHC("Alertness",1),
		new kantia.template.npcHC("Attack Precision",1),
		new kantia.template.npcHC("Animal Companion",1),
		new kantia.template.npcHC("Back to the Wall",1),
		new kantia.template.npcHC("Blind Fighting",1),
		new kantia.template.npcHC("Combat Intuition",4),
		new kantia.template.npcHC("Combat Reflexes",8),
		new kantia.template.npcHC("Commanding Presence",1),
		new kantia.template.npcHC("Cool Headed",1),
		new kantia.template.npcHC("Crippling Strike",1),
		new kantia.template.npcHC("Danger Sense",1),
		new kantia.template.npcHC("Dead Eye Aim",1),
		new kantia.template.npcHC("Favored Opponent",1),
		new kantia.template.npcHC("Fearless",1),
		new kantia.template.npcHC("Flashy Warrior",1),
		new kantia.template.npcHC("Intimidating Presence",1),
		new kantia.template.npcHC("Iron Will",1),
		new kantia.template.npcHC("Killing Blow",1),
		new kantia.template.npcHC("Leadership",1),
		new kantia.template.npcHC("Magic Resistance",1),
		new kantia.template.npcHC("Nothing to Lose",1),
		new kantia.template.npcHC("Psychic Resistance",1),
		new kantia.template.npcHC("Shoot 'em All",1),
		new kantia.template.npcHC("Steadfast",1),
		new kantia.template.npcHC("Tactician",1),
		new kantia.template.npcHC("Take 'em All",1),
		new kantia.template.npcHC("The Stare",1),
		new kantia.template.npcHC("Thich Skinned",2),
		new kantia.template.npcHC("Tough as Nails",2),
		new kantia.template.npcHC("Weapon Master",1),
		new kantia.template.npcHC("Weapon Shield",1),
		new kantia.template.npcHC("Weapon Technique",1)
	],
	["Chain Shirt","Reinforced Bracers"],
	{
		"melee": kantia.lists.weapons.melee.all.slice(),
		"ranged": kantia.lists.weapons.ranged.all.slice()
	},
	"",
	"Experienced military NPCs like this tend to carry good to high quality equipment. Some of it may actually be much better than standard issue. While they may not always carry money on themselves, it wouldn't be uncommon to find. High-Level fighting types usually carry about 2d6 crowns, 2d12 silver, and 2d10 copper.",
	"The fighter template focuses on NPCs that have a talent for traditional melee combat. Many are soldiers, mercenaries, town watch, bandits, and bounty hunters. They are well-skilled and capable individuals that are equally efficient if working alone or with others. They lead rough and often very dangerous lives and their personalities and attitudes will reflect that. NPC Fighters are vaguely classified into three types: basic, expert, and master.",
	[]
);